=== drgraetz/os/src/buildinfo.dtd
<!-- The root element of buildinfo.xml -->
<!ELEMENT build-info (platform+,signature*,tool*)>

<!-- The definition of a target platform. A platform is referenced by
     its _name_.
     
     For each platform, the following must be defined:
     - compiler parameters
     - the name of the qemu executable
     - qemu parameters
     - the cpu on which it is run as it is passed as -mcpu parameter to the
       assembler and as -mtune parameter to the compiler
     
     Multiple symbols may be defined, which are used to invoke the linker. -->
<!ELEMENT platform (linker-symbol*)>
<!ATTLIST platform
    name                ID              #REQUIRED
    target-triplet      CDATA           #REQUIRED
    compiler-params     CDATA           #REQUIRED
    qemu-params         CDATA           #REQUIRED
    qemu                CDATA           #REQUIRED
    cpu                 CDATA           #REQUIRED>

<!-- The definition of a symbol which is passed to the linker using the
	 -defsym command line option -->
<!ELEMENT linker-symbol EMPTY>
<!ATTLIST linker-symbol
	name				CDATA			#REQUIRED
	value				CDATA			#REQUIRED>

<!-- The definition of a signature. A signature is valid for an URI and all
     sub-URIs. It uses a public-key (which is downloaded using gpg -key-recv)
     and may be contained in a key-ring, which is defined by its URL. The
     signature file is determined by another extension, that is added to the
     URL of the signed file.-->
<!ELEMENT signature EMPTY>
<!ATTLIST signature
	uri					CDATA			#REQUIRED
	public-key			CDATA			#IMPLIED
	key-ring			CDATA			#IMPLIED
	extension			CDATA			#REQUIRED>

<!-- The definition of a 3rd party tool. A third party tool is identified by
	 its name and consists of one or multiple packets. It may be
	 target-dependent (e.g. the GNU binutils), i.e. for each target platform
	 the tool has to be recompiled. An optional set of environment variables
	 may be defined. A list of executables, which are shipped with the tool,
	 may be defined. If no executables are listed, it is assumed, that a
	 single executable named after the tool is provided.-->
<!ELEMENT tool (env*,package+,executable*)>
<!ATTLIST tool
	name				ID				#REQUIRED
	target-dependent	CDATA			#IMPLIED>

<!-- The definition of an executable with its name, which is provided by a
	 tool. -->
<!ELEMENT executable EMPTY>
<!ATTLIST executable
	name				CDATA			#REQUIRED>

<!-- The definition of a software package, which is downloaded on demand
	 from a given URL. It may contain sub-packages. -->
<!ELEMENT package (sub-package*)>
<!ATTLIST package
	url					CDATA			#REQUIRED>

<!-- The definition of a software sub-package, which is downloaded on demand
	 from a given URL into a directory of the unpackaged main-package. It
	 may contain nested sub-packages. -->
<!ELEMENT sub-package (sub-package*)>
<!ATTLIST sub-package
	url					CDATA			#REQUIRED
	dir					CDATA			#REQUIRED>

<!-- The definition of an environment variable with its value. -->
<!ELEMENT env EMPTY>
<!ATTLIST env
	variable			CDATA			#REQUIRED
	value				CDATA			#REQUIRED>

=== drgraetz/os/src/buildinfo.xml
<?xml version='1.0'?>
<!DOCTYPE build-info SYSTEM 'buildinfo.dtd'>

<build-info>

    
	<platform name='i386' target-triplet='i686-elf' cpu='i386'
		compiler-params=''
		qemu='qemu-system-i386' qemu-params=''>
		<linker-symbol name='bootAddr' value='0x00100000'/>
		<linker-symbol name='kernelAddr' value='0xFFC00000'/>
        <linker-symbol name='pageSize' value='4096'/>
	</platform>
	
	<!-- mfpu=vfp -->
	<platform name='rpi' target-triplet='arm-elf-eabi' cpu='arm1176jzf-s'
		compiler-params='-mfloat-abi=hard'
		qemu='qemu-system-arm' qemu-params='-M raspi -cpu arm1176 -m 256'>
        <linker-symbol name='bootAddr' value='0x00008000'/>
        <linker-symbol name='kernelAddr' value='0xFFF08000'/>
        <linker-symbol name='pageSize' value='4096'/>
	</platform>
	
	<signature uri='llvm.org' public-key='02119294' extension='.sig'/>
	<signature uri='ftp.gnu.org/gnu' key-ring='https://ftp.gnu.org/gnu/gnu-keyring.gpg' extension='.sig'/>

	<tool name='clang'>
		<!-- required on Cygwin, as otherwise the number of segments exceeds the permitted maximum -->
		<env variable='CXXFLAGS' value='-Og'/>
		<package url='http://llvm.org/releases/3.8.1/llvm-3.8.1.src.tar.xz'>
			<sub-package url='http://llvm.org/releases/3.8.1/cfe-3.8.1.src.tar.xz' dir='tools/clang'/>
		</package>
	</tool>
	
	<tool name='binutils' target-dependent='true'>
		<package url='https://ftp.gnu.org/gnu/binutils/binutils-2.26.tar.bz2'/>
		<executable name='ld'/>
	</tool>
	
	<tool name='gdb' target-dependent='true'>
	   <package url='https://ftp.gnu.org/gnu/gdb/gdb-7.11.tar.xz'/>
	</tool>

</build-info>
